### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]

### ISSUE THREAD

**Issue by romanstech** [Steve-Mcl/node-red-contrib-cron-plus#7]
node works excellent except errors below. It doesn't break a functionality but I see these errors in node-red-logs each time I change something in cronjob window. I mean window with drop-down description. These errors are not critical but I prefer to inform you.

```
> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
> at ServerResponse.setHeader (_http_outgoing.js:470:11)
> at ServerResponse.header (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:771:10)
> at ServerResponse.contentType (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:599:15)
> at ServerResponse.sendStatus (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:357:8)
> at /home/nodered/.node-red/node_modules/node-red-contrib-cron-plus/cronplus.js:709:8
> at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
> at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
> at /usr/lib/node_modules/node-red/node_modules/@node-red/editor-api/lib/auth/index.js:74:13
> at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
> at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
> at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
> at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
> at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
> at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
> at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
> at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
> at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
> at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
> at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
> at query (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/query.js:45:5)
> at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
> at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
> at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
> at Function.handle (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:174:3)
```

**Comment by Steve-Mcl** [comment]
thanks for the info 

I'm not certain where exactly you are seeing these & I'm not sure how they can be related.

could you provide more info? e.g. nodejs version, using https? self cert? via the internet or all localhost?

Perhaps you could also paste a screenshot into the reply?

**Comment by Steve-Mcl** [comment]
Hi please reopen this issue of the problem persists or returns.
