### ISSUE TITLE
Error: WARNING: Date in past. Will never be fired.

### ISSUE THREAD

**Issue by m-schaeffler** [Steve-Mcl/node-red-contrib-cron-plus#73]
Node-Red crashed with this log entries:

```
18 Nov 22:36:03 - [red] Uncaught Exception:
18 Nov 22:36:03 - [error] Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/srv/node-red/.node-red/node_modules/cron/dist/time.js:93:23)
    at CronTime.getTimeout (/srv/node-red/.node-red/node_modules/cron/dist/time.js:110:34)
    at Timeout.callbackWrapper [as _onTimeout] (/srv/node-red/.node-red/node_modules/cron/dist/job.js:119:48)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 50min 29.062s CPU time.
nodered.service: Scheduled restart job, restart counter is at 2.
Stopped nodered.service - Node-RED graphical event wiring tool.
nodered.service: Consumed 50min 29.062s CPU time.
Starting nodered.service - Node-RED graphical event wiring tool...
Started nodered.service - Node-RED graphical event wiring tool.
18 Nov 22:36:26 - [info]
Willkommen bei Node-RED

18 Nov 22:36:26 - [info] Node-RED Version: v3.1.0
18 Nov 22:36:26 - [info] Node.js  Version: v20.5.1
18 Nov 22:36:26 - [info] Linux 6.1.0-rpi6-rpi-v7l arm LE
18 Nov 22:36:29 - [info] Paletten-Nodes werden geladen
18 Nov 22:36:33 - [info] Dashboard version 3.6.1 started at /ui
```

Environment:
-     Node-RED version: 3.1.0
-     Node.js version: 20.5.1
-     npm version:
-     Platform/OS: Raspberry OS bookworm
-     Browser: no connection at this time

**Comment by m-schaeffler** [comment]
This happens several times a week.

**Comment by m-schaeffler** [comment]
sorry, wrong node
